In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [3]:
#EJERCICIO 1

import pandas as pd
import tkinter as tk
from tkinter import filedialog

ventana = tk.Tk()
ventana.withdraw()
ventana.attributes('-topmost', True)

ruta = filedialog.askopenfilename(
    title="Selecciona el archivo CSV",
    filetypes=[("Archivos CSV", "*.csv")]
)

ventana.destroy()

dfempleado = pd.read_csv(ruta).set_index('id_empleado')
dfempleado.head()

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1002,Elena Sanz,RRHH,Madrid,22000.0,2022-08-16,1.0
1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
1004,Laura Gomez,Marketing,Sevilla,24900.0,2023-05-21,3.0
1005,Paula Torres,RRHH,Madrid,54800.0,2019-01-18,5.0

In [5]:
dfempleado.head()

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1002,Elena Sanz,RRHH,Madrid,22000.0,2022-08-16,1.0
1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
1004,Laura Gomez,Marketing,Sevilla,24900.0,2023-05-21,3.0
1005,Paula Torres,RRHH,Madrid,54800.0,2019-01-18,5.0

In [6]:
dfempleado.columns

Index(['nombre', 'departamento', 'ciudad', 'salario', 'fecha_contratacion',
       'evaluacion'],
      dtype='str')

In [7]:
#EJERCICIO 2
dfempleado[["nombre","departamento","salario"]]

                   nombre departamento  salario
id_empleado
1001           Marta Ruiz     Finanzas  44300.0
1002           Elena Sanz         RRHH  22000.0
1003           Ana Prieto       Ventas  58200.0
1004          Laura Gomez    Marketing  24900.0
1005         Paula Torres         RRHH  54800.0
...                   ...          ...      ...
1086         Nuria Torres  Operaciones  29700.0
1087           Diego Sanz         RRHH  36200.0
1088         Lucia Prieto  Operaciones  28500.0
1089         Sergio Gomez         RRHH  51600.0
1090            Ana Gomez    Marketing  41400.0

[90 rows x 3 columns]

In [8]:

#EJERCICIO 3
dfempleado.loc[[1003,1007,1015],["nombre","departamento","salario"]]

                   nombre departamento  salario
id_empleado
1003           Ana Prieto       Ventas  58200.0
1007         Javier Nieto           IT  44400.0
1015           Sofia Mora           IT  37100.0

In [10]:
#EJERCICIO 4
dfempleado.iloc[0:10,1:3]

            departamento     ciudad
id_empleado
1001            Finanzas   Valencia
1002                RRHH     Madrid
1003              Ventas     Bilbao
1004           Marketing    Sevilla
1005                RRHH     Madrid
1006            Finanzas   Valencia
1007                  IT   Valencia
1008         Operaciones  Barcelona
1009         Operaciones     Madrid
1010            Finanzas    Sevilla

In [11]:
#EJERCICIO 5
dfempleado.sort_values('salario', ascending=False).head()

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1032,Diego Gomez,Marketing,Madrid,59500.0,2023-07-14,5.0
1053,Laura Torres,IT,Barcelona,59400.0,2016-03-30,1.0
1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
1062,Diego Prieto,RRHH,Madrid,55600.0,2015-01-06,1.0

In [12]:
#EJERCICIO 6
dfempleado.sort_values(['departamento','salario'], ascending=[True,False])#.head()

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
1006,Lucia Mora,Finanzas,Valencia,49200.0,2022-03-25,3.0
1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1055,Carlos Ortiz,Finanzas,Sevilla,43200.0,2019-07-21,3.0
1039,Marta Gomez,Finanzas,Valencia,42900.0,2016-11-05,1.0
...,...,...,...,...,...,...
1054,Pedro Gomez,Ventas,Madrid,41400.0,2022-02-25,2.0
1063,Sofia Torres,Ventas,Barcelona,40000.0,2019-08-31,NaN
1024,Sergio Torres,Ventas,Madrid,25400.0,2019-09-30,3.0
1020,Javier Sanz,Ventas,Madrid,22000.0,2018-02-15,5.0
1048,Sofia Ferrer,Ventas,Barcelona,22000.0,2017-09-16,2.0